language: csharp  
sudo: required
dist: bionic
addons:
  apt:
    packages:
    - unzip
    - git
    - libc6
    - libc6-dev
    - libc6-dbg

env:  
  - CLI_VERSION=latest DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
dotnet: 2.2.100
mono: latest
os:  
  - linux
branches:  
  only:
    - master
    - /^v[0-9]+.*/
install: 
  - chmod +x ./install-gitversion.sh
  - ./install-gitversion.sh
script:  
  - chmod +x ./ci-script.sh
  - ./ci-script.sh
