language: csharp  
sudo: required
dist: bionic
env:  
  - CLI_VERSION=latest DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
dotnet: 2.2.100
mono: none
os:  
  - linux
branches:  
  only:
    - master
    - /^v[0-9]+.*/
script:  
  - chmod +x ./ci-script.sh
  - ./ci-script.sh
